grid_resolution: [0.5, 0.5]
x_range: [-10, 10]
y_range: [-15, 15]
z_max: 1.0
roi_bounds: [-20, 20, -20, 22.09, -2.4, 1]
ransac:
  distance_threshold: 0.3
  ransac_n: 3
  num_iterations: 5000
farneback_params:
  pyr_scale: 0.5
  levels: 3
  winsize: 15
  iterations: 3
  poly_n: 5
  poly_sigma: 1.2
  flags: 0
masks:
  alpha_p: [0.8]
  alpha_cont: [0.2]
dt: 1.0
pcd_file1: "C:/Users/anvit/Desktop/Desktop/Fall_24/MR/Project/DATMO/GT2/Varying_velocity_single_target/Varying_velocity_single_target/PCD/lidar_frame_0060.pcd"
pcd_file2: "C:/Users/anvit/Desktop/Desktop/Fall_24/MR/Project/DATMO/GT2/Varying_velocity_single_target/Varying_velocity_single_target/PCD/lidar_frame_0090.pcd"
pcd_file3: "C:/Users/anvit/Desktop/Desktop/Fall_24/MR/Project/DATMO/GT2/Varying_velocity_single_target/Varying_velocity_single_target/PCD/lidar_frame_0120.pcd"
# pcd_file1: "C:/Users/anvit/Desktop/Desktop/Fall_24/MR/Project/DATMO/GT2/test_2_GT_PCD/test_2_GT_PCD/lidar_frame_1140.pcd"
# pcd_file2: "C:/Users/anvit/Desktop/Desktop/Fall_24/MR/Project/DATMO/GT2/test_2_GT_PCD/test_2_GT_PCD/lidar_frame_1170.pcd"
# pcd_file3: "C:/Users/anvit/Desktop/Desktop/Fall_24/MR/Project/DATMO/GT2/test_2_GT_PCD/test_2_GT_PCD/lidar_frame_1200.cd"
# pcd_file1: "C:/Users/anvit/Desktop/Desktop/Fall_24/MR/Project/DATMO/GT2/test_2_GT_PCD/test_2_GT_PCD/lidar_frame_0360.pcd"
# pcd_file2: "C:/Users/anvit/Desktop/Desktop/Fall_24/MR/Project/DATMO/GT2/test_2_GT_PCD/test_2_GT_PCD/lidar_frame_0450.pcd"
