grid_resolution:
  - [1.0, 1.0]
  - [2.0, 2.0]
x_range: [-50, 50]
y_range: [-50, 50]
z_max: 5.0
roi_bounds: [-20, 20, -20, 22.09, -2.4, 1]
farneback_params:
  pyr_scale: 0.5
  levels: 3
  winsize: 15
  iterations: 3
  poly_n: 5
  poly_sigma: 1.2
  flags: 0
masks:
  alpha_p: [0.3, 0.5, 0.7]
  alpha_cont: [0.4, 0.5, 0.6]
dt: 1.0
pcd_file1: "C:/Users/anvit/Desktop/Desktop/Fall_24/MR/Project/DATMO/GT2/test_2_GT_PCD/test_2_GT_PCD/lidar_frame_0030.pcd"
pcd_file2: "C:/Users/anvit/Desktop/Desktop/Fall_24/MR/Project/DATMO/GT2/test_2_GT_PCD/test_2_GT_PCD/lidar_frame_0090.pcd"
